# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: node:12
#
#pipelines:
#  default:
#    - step: &testStep
#        name: Test
#        caches:
#          - node
#        script: # Modify the commands below to build your repository.
#          - npm install
#          - npm run build
#          - npm test
#  branches:
#    master:
#      - step: *testStep
#      - step:
#          name: Publish
#          caches:
#            - node
#          script:
#            - npm version "1.0.${BITBUCKET_BUILD_NUMBER}" -m "%s [skip ci]"
#            - npm install
#            - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
#            - npm publish --unsafe-perm
